## This file will run all the code in order

exec(open("./src/data_prep.py").read()) ## takes data files and converts them into a format that LibSVM can read
exec(open("./src/run_svm.py").read()) ## Trains and tests the OCSVM model
exec(open("./src/metrics.py").read()) ## Runs metrics on the test results generated by the OCSVM